title: Rosh Beed
description: DevOps Consultant
url: "www.roshbeed.com" 
username: Rosh Beed
user_subtitle: DevOps Consultant
user_description: I’m a life-long learner. I dive deep into understanding how things work and keeping up to date with the latest technologies. I create innovative yet simple solutions to complex problems and support customers on their journey to the cloud.
email: rosh.beed@gmail.com
twitter_username: roshbeed
github_username:  roshbeed
linkedin_username:  roshbeed
sass:
  sass_dir: css
  style: compressed
collections_dir:
  my_collections
collections:
  jobs:
  educations:
  certifications:
