title: Rosh Beed
description: DevOps
url: "www.roshbeed.com" 
username: Rosh Beed
user_subtitle: DevOps
user_description: Hi, I’m Rosh, a life-long learner. I push myself to dive deep into understanding how things work and keeping up to date with the latest cutting edge technologies. I think about innovative ways to create simple solutions to complex problems. I have strong interpersonal skills and technical knowledge to provide better support to customers in their journey to the cloud. 
email: rosh.beed@gmail.com
twitter_username: roshbeed
github_username:  roshbeed
linkedin_username:  roshbeed
sass:
  sass_dir: css
  style: compressed
collections_dir:
  my_collections
collections:
  jobs:
  educations:
  certifications:
