title: Rosh Beedassee
description: DevOps Engineer
url: "www.beedassee.com" 
username: Rosh Beedassee
user_subtitle: DevOps Engineer
user_description: Hi, I am Rosh, a recent Computer Science graduate. I'm drawn to understanding how things work and finding effective solutions to problems. I'm Interested in keeping up to date with the latest technologies.
email: rosh@beedassee.com
twitter_username: roshbeed
github_username:  roshbeed
linkedin_username:  roshbeed
sass:
  sass_dir: css
  style: compressed
collections_dir:
  my_collections
collections:
  jobs:
    output: true
  educations:
    output: true
