version: 0.2
phases:
  install:
    commands: 
      - mkdir .jekyll-cache
  build:
    commands:
      - jekyll build --trace
  post_build:
    commands:
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: _site/
