version: 0.2
phases:
  install:
    commands: gem install bundler          
  build:
    commands:
      - jekyll build
  post_build:
    commands:
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: _site/
